/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/O8HOcpeRM8N
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function v0-button-component() {
  return (
    <div className="flex justify-center mt-4">
      <Button variant="outline" onClick={handleRandom}>
        Random
      </Button>
    </div>
  )
}
