/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tsvCiUypIaE
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"

export function V0-Table-Component() {
  const dishes = [
    { id: 1, name: "Margherita Pizza", orders: 1234 },
    { id: 2, name: "Beef Burger", orders: 987 },
    { id: 3, name: "Chicken Tikka Masala", orders: 876 },
    { id: 4, name: "Vegetable Stir-Fry", orders: 654 },
    { id: 5, name: "Spaghetti Bolognese", orders: 543 },
    { id: 6, name: "Grilled Salmon", orders: 432 },
    { id: 7, name: "Pad Thai", orders: 321 },
    { id: 8, name: "Caesar Salad", orders: 210 },
  ]
  const [sortedDishes, setSortedDishes] = useState(dishes.sort((a, b) => b.orders - a.orders))
  const handleSort = () => {
    setSortedDishes(sortedDishes.sort((a, b) => b.orders - a.orders))
  }
  return (
    <div className="bg-background text-foreground p-8 sm:p-12 md:p-16">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl font-bold mb-8">Most Popular Dishes</h1>
        <div className="bg-card rounded-lg shadow-lg overflow-hidden">
          <table className="w-full table-auto">
            <thead>
              <tr className="bg-muted text-muted-foreground">
                <th className="px-4 py-3 text-left">Progress</th>
                <th className="px-4 py-3 text-right">Orders</th>
                <th className="px-4 py-3 text-left cursor-pointer" onClick={handleSort}>
                  Dish <ArrowUpDownIcon className="w-4 h-4 inline-block ml-2" />
                </th>
              </tr>
            </thead>
            <tbody>
              {sortedDishes.map((dish) => (
                <tr key={dish.id} className="border-b border-muted/20">
                  <td className="px-4 py-3 text-left">
                    <div className="w-full bg-muted rounded-full h-2.5">
                      <div
                        className="bg-primary h-2.5 rounded-full"
                        style={{ width: `${(dish.orders / sortedDishes[0].orders) * 100}%`, marginLeft: "auto" }}
                      />
                    </div>
                  </td>
                  <td className="px-4 py-3 text-right font-bold">{dish.orders}</td>
                  <td className="px-4 py-3 text-left">{dish.name}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}

function ArrowUpDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m21 16-4 4-4-4" />
      <path d="M17 20V4" />
      <path d="m3 8 4-4 4 4" />
      <path d="M7 4v16" />
    </svg>
  )
}
